export default {
  root: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    height: "90vh",
  },
  card: {
    position: "relative",
    width: 400,
    height: 400,
    display: "grid",
    placeItems: "center",
  },
  name: { textTransform: "capitalize" },
  sprite: {
    display: "block",
    filter: "drop-shadow(2px 2px 4px #000)",
    imageRendering: "pixelated",
  },
  typeList: { listStyle: "none", display: "flex", gap: 6, padding: 6 },
  type: {
    textTransform: "capitalize",
    padding: "3px 6px",
    borderRadius: 3,
    textShadow: "1px 1px 2px #000",
    color: "#FFF",
  },
  loader: { height: 0, margin: 0 },
  background: {
    position: "absolute",
    top: 0,
    left: 0,
    height: "100%",
    width: "100%",
    zIndex: "-1",
    overflow: "hidden",
    borderRadius: 3,
  },
  backgroundLeft: {
    position: "absolute",
    top: "0",
    left: "0",
    height: "141.7%",
    width: "141.7%",
    transform: "translate(-50%, -50%) rotate(45deg)",
  },
  backgroundRight: {
    position: "absolute",
    top: "100%",
    left: "100%",
    height: "141.7%",
    width: "141.7%",
    transform: "translate(-50%, -50%) rotate(45deg)",
  },
} as any;
